sudo: required
services:
  - docker

before_install:
  - docker build -t sachin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sachinkokate525/docker-react npm run test -- --coverage